/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorCard: typeof import('./src/components/AuthorCard/index.vue')['default']
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    BarrageCard: typeof import('./src/components/BarrageCard/index.vue')['default']
    CommentCard: typeof import('./src/components/CommentCard/index.vue')['default']
    FavDialog: typeof import('./src/components/FavDialog/index.vue')['default']
    HistoryCard: typeof import('./src/components/HistoryCard/index.vue')['default']
    HistoryCardSkeleton: typeof import('./src/components/HistoryCard/HistoryCardSkeleton.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoginRegisterDialog: typeof import('./src/components/LoginRegisterDialog/index.vue')['default']
    NavUserCard: typeof import('./src/components/NavUserCard/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search/SearchInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VideoAction: typeof import('./src/components/VideoAction/index.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard/index.vue')['default']
    VideoCardCover: typeof import('./src/components/VideoCard/component/VideoCardCover.vue')['default']
    VideoCardInfo: typeof import('./src/components/VideoCard/component/VideoCardInfo.vue')['default']
    VideoList: typeof import('./src/components/VideoList/index.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer/index.vue')['default']
  }
}
